name: Deploy React App to S3 (app.gostride.co)

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Build & Deploy
    runs-on: ubuntu-latest

    env:
      AWS_REGION: us-west-2  # ✅ Replace with your region
      BUCKET_NAME: app.gostride.co

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'
          cache-dependency-path: client/package-lock.json

      - name: Install dependencies with cache
        run: |
          cd client
          npm ci

      - name: Build React App
        run: |
          cd client
          npm run build

      - name: Deploy to S3
        run: |
          aws s3 sync client/build s3://$BUCKET_NAME --region $AWS_REGION --delete
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}